import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Serene Blossom Gown',
    price: 250,
    image: 'https://placehold.co/600x800.png',
    category: 'Dresses',
    trending: true,
    description: 'A flowing floral gown perfect for spring weddings and garden parties. Made from the finest silk chiffon.',
    dataAiHint: 'floral gown',
  },
  {
    id: '2',
    name: 'Midnight Velvet Dress',
    price: 320,
    image: 'https://placehold.co/600x800.png',
    category: 'Dresses',
    trending: false,
    description: 'A luxurious velvet dress with a classic silhouette, ideal for formal evening events.',
    dataAiHint: 'velvet dress',
  },
  {
    id: '3',
    name: 'Golden Radiance Necklace',
    price: 120,
    image: 'https://placehold.co/600x800.png',
    category: 'Accessories',
    trending: true,
    description: 'A stunning 18k gold-plated necklace with a unique sunburst pendant. The perfect statement piece.',
    dataAiHint: 'gold necklace',
  },
  {
    id: '4',
    name: 'City Sleek Combo',
    price: 450,
    image: 'https://placehold.co/600x800.png',
    category: 'Combos',
    trending: true,
    description: 'The ultimate urban chic look: our best-selling blazer paired with a silk camisole and tailored trousers.',
    dataAiHint: 'chic outfit',
  },
  {
    id: '5',
    name: 'The Parisian Day Dress',
    price: 180,
    image: 'https://placehold.co/600x800.png',
    category: 'Dresses',
    trending: true,
    description: 'Effortlessly chic, this linen-blend dress features a belted waist and puff sleeves for a touch of romance.',
    dataAiHint: 'linen dress',
  },
  {
    id: '6',
    name: 'Pearl Drop Earrings',
    price: 85,
    image: 'https://placehold.co/600x800.png',
    category: 'Accessories',
    trending: false,
    description: 'Elegant freshwater pearl earrings that add a touch of timeless sophistication to any outfit.',
    dataAiHint: 'pearl earrings',
  },
  {
    id: '7',
    name: 'Weekend Getaway Set',
    price: 280,
    image: 'https://placehold.co/600x800.png',
    category: 'Combos',
    trending: false,
    description: 'A comfortable yet stylish knit sweater and matching wide-leg pants. Perfect for travel or a cozy weekend.',
    dataAiHint: 'knit set',
  },
  {
    id: '8',
    name: 'Scarlet Ruffle Dress',
    price: 295,
    image: 'https://placehold.co/600x800.png',
    category: 'Dresses',
    trending: false,
    description: 'A bold and beautiful dress in a striking scarlet hue, featuring delicate ruffles along the neckline.',
    dataAiHint: 'red dress',
  },
  {
    id: '9',
    name: 'Emerald Isle Gown',
    price: 350,
    image: 'https://placehold.co/600x800.png',
    category: 'Dresses',
    trending: false,
    description: 'A stunning emerald green gown with a thigh-high slit and intricate beading.',
    dataAiHint: 'green dress',
  },
  {
    id: '10',
    name: 'Azure Dream Dress',
    price: 275,
    image: 'https://placehold.co/600x800.png',
    category: 'Dresses',
    trending: true,
    description: 'A light and airy dress in a beautiful azure blue, perfect for a beach vacation.',
    dataAiHint: 'blue dress',
  },
  {
    id: '11',
    name: 'Silver Lining Bracelet',
    price: 95,
    image: 'https://placehold.co/600x800.png',
    category: 'Accessories',
    trending: false,
    description: 'A delicate sterling silver bracelet with a modern, minimalist design.',
    dataAiHint: 'silver bracelet',
  },
  {
    id: '12',
    name: 'Gala Ready Combo',
    price: 550,
    image: 'https://placehold.co/600x800.png',
    category: 'Combos',
    trending: true,
    description: 'A complete evening look with a floor-length gown, matching clutch, and sparkling earrings.',
    dataAiHint: 'evening gown',
  },
];
