import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Serene Blossom Gown',
    price: 250,
    image: 'https://placehold.co/600x800.png',
    category: 'Dresses',
    trending: true,
    description: 'A flowing floral gown perfect for spring weddings and garden parties. Made from the finest silk chiffon.',
    dataAiHint: 'floral gown',
  },
  {
    id: '2',
    name: 'Midnight Velvet Dress',
    price: 320,
    image: 'https://placehold.co/600x801.png',
    category: 'Dresses',
    trending: false,
    description: 'A luxurious velvet dress with a classic silhouette, ideal for formal evening events.',
    dataAiHint: 'velvet dress',
  },
  {
    id: '3',
    name: 'Golden Radiance Necklace',
    price: 120,
    image: 'https://placehold.co/600x802.png',
    category: 'Accessories',
    trending: true,
    description: 'A stunning 18k gold-plated necklace with a unique sunburst pendant. The perfect statement piece.',
    dataAiHint: 'gold necklace',
  },
  {
    id: '4',
    name: 'City Sleek Combo',
    price: 450,
    image: 'https://placehold.co/600x803.png',
    category: 'Combos',
    trending: true,
    description: 'The ultimate urban chic look: our best-selling blazer paired with a silk camisole and tailored trousers.',
    dataAiHint: 'chic outfit',
  },
  {
    id: '5',
    name: 'The Parisian Day Dress',
    price: 180,
    image: 'https://placehold.co/600x804.png',
    category: 'Dresses',
    trending: true,
    description: 'Effortlessly chic, this linen-blend dress features a belted waist and puff sleeves for a touch of romance.',
    dataAiHint: 'linen dress',
  },
  {
    id: '6',
    name: 'Pearl Drop Earrings',
    price: 85,
    image: 'https://placehold.co/600x805.png',
    category: 'Accessories',
    trending: false,
    description: 'Elegant freshwater pearl earrings that add a touch of timeless sophistication to any outfit.',
    dataAiHint: 'pearl earrings',
  },
  {
    id: '7',
    name: 'Weekend Getaway Set',
    price: 280,
    image: 'https://placehold.co/600x806.png',
    category: 'Combos',
    trending: false,
    description: 'A comfortable yet stylish knit sweater and matching wide-leg pants. Perfect for travel or a cozy weekend.',
    dataAiHint: 'knit set',
  },
  {
    id: '8',
    name: 'Scarlet Ruffle Dress',
    price: 295,
    image: 'https://placehold.co/600x807.png',
    category: 'Dresses',
    trending: false,
    description: 'A bold and beautiful dress in a striking scarlet hue, featuring delicate ruffles along the neckline.',
    dataAiHint: 'red dress',
  },
  {
    id: '9',
    name: 'Emerald Isle Gown',
    price: 350,
    image: 'https://placehold.co/600x808.png',
    category: 'Dresses',
    trending: false,
    description: 'A stunning emerald green gown with a thigh-high slit and intricate beading.',
    dataAiHint: 'green dress',
  },
  {
    id: '10',
    name: 'Azure Dream Dress',
    price: 275,
    image: 'https://placehold.co/600x809.png',
    category: 'Dresses',
    trending: true,
    description: 'A light and airy dress in a beautiful azure blue, perfect for a beach vacation.',
    dataAiHint: 'blue dress',
  },
  {
    id: '11',
    name: 'Silver Lining Bracelet',
    price: 95,
    image: 'https://placehold.co/600x810.png',
    category: 'Accessories',
    trending: false,
    description: 'A delicate sterling silver bracelet with a modern, minimalist design.',
    dataAiHint: 'silver bracelet',
  },
  {
    id: '12',
    name: 'Gala Ready Combo',
    price: 550,
    image: 'https://placehold.co/600x811.png',
    category: 'Combos',
    trending: true,
    description: 'A complete evening look with a floor-length gown, matching clutch, and sparkling earrings.',
    dataAiHint: 'evening gown',
  },
  {
    id: '13',
    name: 'Classic White Shirt',
    price: 75,
    image: 'https://placehold.co/600x812.png',
    category: 'Shirts',
    trending: false,
    description: 'A crisp, timeless white button-down shirt. A wardrobe essential.',
    dataAiHint: 'white shirt',
  },
  {
    id: '14',
    name: 'High-Waisted Trousers',
    price: 110,
    image: 'https://placehold.co/600x813.png',
    category: 'Pants',
    trending: true,
    description: 'Flattering high-waisted trousers in a versatile beige color.',
    dataAiHint: 'beige trousers',
  },
  {
    id: '15',
    name: 'Performance Leggings',
    price: 90,
    image: 'https://placehold.co/600x814.png',
    category: 'Sportswear',
    trending: true,
    description: 'High-performance leggings for any workout, with moisture-wicking fabric.',
    dataAiHint: 'black leggings',
  },
  {
    id: '16',
    name: 'Black Tie Jumpsuit',
    price: 420,
    image: 'https://placehold.co/600x815.png',
    category: 'Formals',
    trending: false,
    description: 'An elegant black jumpsuit that is a modern alternative to a formal gown.',
    dataAiHint: 'black jumpsuit',
  },
   {
    id: '17',
    name: 'Boho Chic Blouse',
    price: 88,
    image: 'https://placehold.co/600x816.png',
    category: 'Shirts',
    trending: true,
    description: 'A breezy, bohemian-style blouse with delicate embroidery.',
    dataAiHint: 'boho blouse',
  },
  {
    id: '18',
    name: 'Distressed Denim',
    price: 130,
    image: 'https://placehold.co/600x817.png',
    category: 'Pants',
    trending: false,
    description: 'Perfectly distressed jeans for a relaxed, stylish look.',
    dataAiHint: 'distressed jeans',
  },
  {
    id: '19',
    name: 'Racerback Tank',
    price: 45,
    image: 'https://placehold.co/600x818.png',
    category: 'Sportswear',
    trending: false,
    description: 'A breathable racerback tank top, perfect for the gym or a run.',
    dataAiHint: 'workout tank',
  },
  {
    id: '20',
    name: 'Little Black Dress',
    price: 280,
    image: 'https://placehold.co/600x819.png',
    category: 'Formals',
    trending: true,
    description: 'The iconic little black dress, updated with a modern, sleek silhouette.',
    dataAiHint: 'black dress',
  },
  {
    id: '21',
    name: 'Linen Summer Shorts',
    price: 65,
    image: 'https://placehold.co/600x820.png',
    category: 'Casuals',
    trending: true,
    description: 'Lightweight and breathable linen shorts for warm summer days.',
    dataAiHint: 'linen shorts',
  },
  {
    id: '22',
    name: 'Graphic Tee',
    price: 50,
    image: 'https://placehold.co/600x821.png',
    category: 'Casuals',
    trending: false,
    description: 'A soft cotton graphic tee with a vintage-inspired design.',
    dataAiHint: 'graphic tee',
  },
];
